### ISSUE TITLE
Update the table example

### ISSUE THREAD

**Issue by viroulep** [cubingusa/compscript#55]
This is the table in the readme:
```
Table(
  Persons(And(Registered(), (FirstName() == "Luke"))),
  [Column("Name", Name()),
   Column("WCA ID", WcaId(), WcaLink()),
   Column("Average", PersonalBest(_333)),
   Column("Single", PersonalBest(_333, "single")),
   Column("psych sheet ranking", PsychSheetPosition(_333))],
  PersonalBest(_333, "average"))
```
It does not seem to work "as-is", and I think it's because of recent changes in the sort functions.

Removing the last arguments makes it work, but loses the sort capabilities: would you have an updated example to sort based on an attribute of the elements?

**Comment by timreyn** [comment]
Whoops, yeah I can update this! You're right, when I added a Sort function, I dropped the extra sort argument in Table().

**Comment by viroulep** [comment]
Awesome thank you!
