### ISSUE TITLE
The function AddPerson doesn't fill person's details

### ISSUE THREAD

**Issue by viroulep** [cubingusa/compscript#57]
I think it's intended, but I'll create an issue just in case: `AddPerson` only add the `wcaUserId` to the person's detail in the WCIF.
I read a bit the activity on the WCA website repository related to non competing staff, and it looks like to me that the intended workflow is the following:
  - compscript adds the person's wcaUserId to the WCIF
  - executing the change on the WCA website makes it create a registration for that user
  - upon subsequent execution in compscript, the person's details actually show up now that the registration exists

Am I correct in how that function is supposed to be used?

I think there are a few actions that can be taken:
  - document the function's behavior, and mention that forgetting to push to the WCA website will lead to incomplete information about persons, and crashes in some cases.
  - optionally compscript could query the WCA website in such cases, to include the user's data right away in the WCIF (which should be fine even if we got them wrong, because they would be erased anyway when the website creates the actual registration).
  - if we don't to query the website for that, we may also include dummy data until the registration is properly create (eg "Imported Person XYZ" with a fake dob); just so that the rest of the script doesn't crash when in "dry-run" mode.

I can definitely take care of 1, but what do you think about doing 2?
If you think it's a corner case I'd definitely be willing to do 3, as I do a lot of "dry-run" things before actually patching the WCIF!

**Comment by timreyn** [comment]
Yes, you're correct. Compscript wasn't designed with the possibility of working locally for a long time without pushing to the WCA site.

I'm not a huge fan of 2, since that seems like it breaks through the dry-run protections. I feel much more comfortable saying "if dry-run then we will never PATCH the WCA site", rather than having to reason about what functions can bypass that.

Related to 3, we could add extra parameters for the rest of the person's details, maybe with defaults like:

```
AddPerson(wcaUserId, name="Fake Name", dob=1970-01-01, ...)
```

what do you think?

**Comment by viroulep** [comment]
Oh I think I wasn't clear for option 2: I was thinking about a GET on `/api/v0/users`, like [this](https://www.worldcubeassociation.org/api/v0/users/277).
Another advantage is that it could be used to "validate" that the user id provided does exist.
But it does mean that we have to emit more calls to the WCA website while executing the script!

I'm definitely fine with your suggestion for option 3: the most important IMO is to prevent a crash on the first few dry-runs execution :)
I'll give it a quick shot in the coming days!
